/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JSONError;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ActionsListAvailableActionsdefaultResponse
 */
public class ActionsListAvailableActionsdefaultResponseTest {
    private final ActionsListAvailableActionsdefaultResponse model = new ActionsListAvailableActionsdefaultResponse();

    /**
     * Model tests for ActionsListAvailableActionsdefaultResponse
     */
    @Test
    public void testActionsListAvailableActionsdefaultResponse() {
        // TODO: test ActionsListAvailableActionsdefaultResponse
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
