/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppImages
 */
public class AppImagesTest {
    private final AppImages model = new AppImages();

    /**
     * Model tests for AppImages
     */
    @Test
    public void testAppImages() {
        // TODO: test AppImages
    }

    /**
     * Test the property 'url16x16'
     */
    @Test
    public void url16x16Test() {
        // TODO: test url16x16
    }

    /**
     * Test the property 'url32x32'
     */
    @Test
    public void url32x32Test() {
        // TODO: test url32x32
    }

    /**
     * Test the property 'url64x64'
     */
    @Test
    public void url64x64Test() {
        // TODO: test url64x64
    }

    /**
     * Test the property 'url128x128'
     */
    @Test
    public void url128x128Test() {
        // TODO: test url128x128
    }

}
