/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AuthenticationsCreateNewAuthenticationRequestData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthenticationsCreateNewAuthenticationRequest
 */
public class AuthenticationsCreateNewAuthenticationRequestTest {
    private final AuthenticationsCreateNewAuthenticationRequest model = new AuthenticationsCreateNewAuthenticationRequest();

    /**
     * Model tests for AuthenticationsCreateNewAuthenticationRequest
     */
    @Test
    public void testAuthenticationsCreateNewAuthenticationRequest() {
        // TODO: test AuthenticationsCreateNewAuthenticationRequest
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
