/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthenticationsCreateNewAuthenticationRequestData
 */
public class AuthenticationsCreateNewAuthenticationRequestDataTest {
    private final AuthenticationsCreateNewAuthenticationRequestData model = new AuthenticationsCreateNewAuthenticationRequestData();

    /**
     * Model tests for AuthenticationsCreateNewAuthenticationRequestData
     */
    @Test
    public void testAuthenticationsCreateNewAuthenticationRequestData() {
        // TODO: test AuthenticationsCreateNewAuthenticationRequestData
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'app'
     */
    @Test
    public void appTest() {
        // TODO: test app
    }

    /**
     * Test the property 'authenticationFields'
     */
    @Test
    public void authenticationFieldsTest() {
        // TODO: test authenticationFields
    }

}
