/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LinksWithPage
 */
public class LinksWithPageTest {
    private final LinksWithPage model = new LinksWithPage();

    /**
     * Model tests for LinksWithPage
     */
    @Test
    public void testLinksWithPage() {
        // TODO: test LinksWithPage
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

    /**
     * Test the property 'prev'
     */
    @Test
    public void prevTest() {
        // TODO: test prev
    }

}
