/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ZapLinks
 */
public class ZapLinksTest {
    private final ZapLinks model = new ZapLinks();

    /**
     * Model tests for ZapLinks
     */
    @Test
    public void testZapLinks() {
        // TODO: test ZapLinks
    }

    /**
     * Test the property 'htmlEditor'
     */
    @Test
    public void htmlEditorTest() {
        // TODO: test htmlEditor
    }

}
