/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ActionsListAvailableActionsdefaultResponse;
import com.konfigthis.client.model.AuthenticationsCreateNewAuthenticationRequest;
import com.konfigthis.client.model.AuthenticationsCreateNewAuthenticationRequestData;
import com.konfigthis.client.model.AuthenticationsCreateNewAuthenticationResponse;
import com.konfigthis.client.model.AuthenticationsGetAvailableResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationsApi
 */
@Disabled
public class AuthenticationsApiTest {

    private static AuthenticationsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AuthenticationsApi(apiClient);
    }

    /**
     * Create Authentication
     *
     * Creates a new Authentication for the provided App.  This endpoint requires the &#x60;authentication:write&#x60; OAuth scope.  This API is rate limited by IP address (60 requests per min), or partner (150 requests per min), whichever occurs first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewAuthenticationTest() throws ApiException {
        AuthenticationsCreateNewAuthenticationRequestData data = null;
        AuthenticationsCreateNewAuthenticationResponse response = api.createNewAuthentication()
                .data(data)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Authentications
     *
     * Fetch the available Authentications for the provided App. This will only return Authentications that are owned by the user and not those that are shared with them, since it&#39;&#39;s not possible to create Zaps with Authentications you don&#39;&#39;t own.  This endpoint requires the &#x60;authentication&#x60; OAuth scope.  This API is rate limited by IP address (60 requests per min), or partner (150 requests per min), whichever occurs first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAvailableTest() throws ApiException {
        UUID app = null;
        Integer limit = null;
        Integer offset = null;
        AuthenticationsGetAvailableResponse response = api.getAvailable(app)
                .limit(limit)
                .offset(offset)
                .execute();
        // TODO: test validations
    }

}
