/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ExperimentalGetZapRunsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ExperimentalApi
 */
@Disabled
public class ExperimentalApiTest {

    private static ExperimentalApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ExperimentalApi(apiClient);
    }

    /**
     * Get Zap Runs
     *
     * This endpoint is a first version tool that delivers basic yet essential details about their executed Zap runs. As an evolving interface, this first version serves foundational information about Zap runs.  _However, it&#39;s important to note that this is an initial implementation and the **response payload is not definitive**. Our aim is to continually iterate and enhance this API, refining its capabilities and data output, to progressively deliver more valuable and useful information in future versions._  This endpoint requires the &#x60;zap:runs&#x60; OAuth scope.  This API is rate limited by IP address (60 requests per min), or partner (150 requests per min), whichever occurs first.  Please note that since this is an experimental tool, if you&#39;re interested in gaining access, you must contact our support team.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getZapRunsTest() throws ApiException {
        String fromDate = null;
        String toDate = null;
        String zapId = null;
        Integer limit = null;
        Integer offset = null;
        String search = null;
        String statuses = null;
        ExperimentalGetZapRunsResponse response = api.getZapRuns()
                .fromDate(fromDate)
                .toDate(toDate)
                .zapId(zapId)
                .limit(limit)
                .offset(offset)
                .search(search)
                .statuses(statuses)
                .execute();
        // TODO: test validations
    }

}
