/*
 * Zapier Embed API
 * The Zapier Embed API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@zapier.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ActionsListAvailableActionsdefaultResponse;
import com.konfigthis.client.model.Zap;
import com.konfigthis.client.model.ZapsCreateZapRequest;
import com.konfigthis.client.model.ZapsCreateZapResponse;
import com.konfigthis.client.model.ZapsGetFilteredZapsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ZapsApi
 */
@Disabled
public class ZapsApiTest {

    private static ZapsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ZapsApi(apiClient);
    }

    /**
     * Create a Zap
     *
     * This URL creates a new Zap based on a series of steps and a given title. &#x60;is_enabled&#x60; must be set to true when creating a new Zap.  This endpoint requires the &#x60;zap:write&#x60; OAuth scope.  This API is rate limited by IP address (60 requests per min), or partner (150 requests per min), whichever occurs first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createZapTest() throws ApiException {
        Zap data = null;
        String expand = null;
        ZapsCreateZapResponse response = api.createZap(data)
                .expand(expand)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Zaps
     *
     * This endpoint returns a list of Zaps for the authenticated Zapier user.  The &#x60;expand&#x60; array can be used to expand selected fields into full objects in the response.  Inputs with keys can also be passed to filter Zaps by certain criteria.  This endpoint requires the &#x60;zap&#x60; OAuth scope.  This API is rate limited by IP address (60 requests per min), or partner (150 requests per min), whichever occurs first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getFilteredZapsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Map<String, String> inputs = null;
        String expand = null;
        ZapsGetFilteredZapsResponse response = api.getFilteredZaps()
                .limit(limit)
                .offset(offset)
                .inputs(inputs)
                .expand(expand)
                .execute();
        // TODO: test validations
    }

}
